apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: sales
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  image: "tiagotxm/spark:3.5-delta-3.0"
  imagePullPolicy: Always
  mainApplicationFile: "s3a://yt-lakehouse/scripts/sales.py"
  sparkConf:
    "spark.hadoop.fs.s3.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.path.style.access": "True"
    "spark.hadoop.fs.s3a.fast.upload": "True"
    "spark.hadoop.fs.s3a.multipart.size": "104857600"
    "fs.s3a.connection.maximum": "100"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension"
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"

  executor:
    cores: 1
    instances: 2
    memory: "512m"
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"